# Generated by Django 5.0.3 on 2024-04-04 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 4, 13, 8, 37, 462100),
                verbose_name="date_time_published",
            ),
        ),
    ]
