# Generated by Django 4.2.11 on 2024-05-05 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0003_tutorialcategory_tutorial_tutorial_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 19, 9, 23, 373066),
                verbose_name="date_time_published",
            ),
        ),
    ]
