# Generated by Django 4.2.11 on 2024-05-05 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0004_alter_tutorial_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 5, 19, 35, 34, 114691),
                verbose_name="date_time_published",
            ),
        ),
        migrations.AlterField(
            model_name="tutorialcategory",
            name="category_slug",
            field=models.CharField(max_length=200),
        ),
    ]
