# Generated by Django 4.2.11 on 2024-05-08 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0005_alter_tutorial_tutorial_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 8, 13, 26, 13, 164498),
                verbose_name="date_time_published",
            ),
        ),
    ]
