# Generated by Django 4.2.11 on 2024-05-13 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0006_alter_tutorial_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 13, 12, 34, 42, 258888),
                verbose_name="date_time_published",
            ),
        ),
    ]
