# Generated by Django 4.2.11 on 2024-05-13 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0007_alter_tutorial_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 13, 13, 26, 36, 410613),
                verbose_name="date_time_published",
            ),
        ),
    ]
