# Generated by Django 4.2.11 on 2024-05-31 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main1", "0008_alter_tutorial_tutorial_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="tutorial_published",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 31, 4, 59, 34, 97542),
                verbose_name="date_time_published",
            ),
        ),
    ]
